# config.py
import os

# ============== Basic Configuration ==============
API_KEY = os.getenv("GEMINI_API_KEY")
if not API_KEY:
    raise RuntimeError("Missing env var GROK_API_KEY")

API_BASE_URL = ""

MODEL_NAME = "gemini-2.5-pro"

TEMPERATURE = 0

EXPERT_PROMPT_TEMPLATE = """
You are a rigorous annotation expert specializing in "decision logic", responsible for verifying whether the 
[Decision Factor Importance Vector] and [Factor Relationship Adjacency Matrix] provided by another model (Agent 1) 
are consistent with the textual rationale.

1. Explanation of Decision Factors (fixed order; all vectors/matrices follow this sequence)
F1: Search Cost Savings —— Search cost savings resulting from privacy sharing / search behavior
F2: Positive Profit      —— Importance of positive profit (>0)
F3: Privacy Loss         —— Privacy loss or privacy risk
F4: Negative Profit      —— Negative profit (<0) or losses
F5: Search Continuation Cost —— Cost of continuing the search process
F6: Net Benefit          —— Net benefit (benefits minus costs/risks)
F7: Profit Maximization  —— Objective of profit maximization
F8: Loss Minimization    —— Loss minimization / risk aversion

2. Input Text and Scenario Information

You will see key information about the consumer in this round of experiments:
- Whether privacy was shared and the rationale (share_reason)
- Final decision to purchase / leave the market and the rationale (final_reason)

These contents are collectively referred to as [Raw Input Data], which are used to determine which factors are truly important 
and whether there are relationships between factors.

[Raw Input Data]:
{input_data}

3. Candidate Annotation Results from Agent 1

You will see two structures generated by Agent 1:
1. importance_vector (Importance Vector)
   - This is a list of length 8, with order strictly corresponding to F1–F8.
   - Each position takes a value of 1, 2, or 3:
     1 = Primary decision driver (most important)
     2 = Secondary but impactful
     3 = Weak effect or basically irrelevant (use 3 if no relevance to the text is observed at all)

2. adjacency_matrix (Factor Relationship Adjacency Matrix)
   - This is an 8×8 binary matrix (0/1 values), with rows and columns ordered by F1–F8.
   - If matrix[i][j] = 1, it indicates:
       Based on the textual rationale, there is a clear decision-making relationship between Factor Fi and Factor Fj,
       e.g., Fi influences Fj, or Fi and Fj were "weighed together" during decision-making.
   - If matrix[i][j] = 0, no clear relationship between these two factors can be identified in the text.

These contents will be provided in JSON format and collectively referred to as [Extraction Results to be Reviewed]:

[Extraction Results to be Reviewed]:
{output_data}

4. Your Review Task and Criteria

Please determine whether the [Extraction Results to be Reviewed] are "generally reasonable" 
**only based on the textual rationale in the [Raw Input Data] (especially share_reason and final_reason)**.

Output 1 (Valid) if the following condition is met:
The vector and adjacency matrix results align with the decision rationale and are reasonable. 
Minor discrepancies with Agent 1's conclusions are acceptable; output 1 as long as you deem the results reasonably acceptable.

Output 0 (Invalid) if any of the following situations occur:
You believe the results do not align with the decision rationale, contain logical fallacies, or have significant errors that are unacceptable.

Note: Differences in opinion are permitted. Only output 0 if you consider the errors significant and unacceptable; 
it is encouraged to output 1 when appropriate.

5. Output Format

Please strictly adhere to the following requirements for your response:
- Output ONLY a single number: 0 or 1
- Do NOT output any explanations or additional comments

Begin reviewing the current data entry now.
"""